{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "077661bf-51e9-449a-98c7-4b44269c1811",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from selenium.webdriver.common.by import By\n",
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "from datetime import date\n",
    "import time\n",
    "import re\n",
    "from urllib.parse import quote\n",
    "import dateparser\n",
    "import io\n",
    "\n",
    "st.set_page_config(page_title=\"📰 Crawler Tin tức\", layout=\"wide\", initial_sidebar_state=\"expanded\")\n",
    "\n",
    "st.title(\"📰 Crawler Tin tức VnExpress & CafeF\")\n",
    "st.markdown(\"**Nhập từ khóa và ngày giới hạn → crawl tự động → tải Excel có hyperlink.**\")\n",
    "\n",
    "# Input giống hệt notebook\n",
    "keywords_str = st.text_input(\n",
    "    \"Nhập từ khóa (cách nhau dấu phẩy):\",\n",
    "    value=\"mwg, thế giới di động, bách hóa xanh, nguyễn đức tài\"\n",
    ")\n",
    "target_date = st.date_input(\n",
    "    \"Ngày giới hạn (lọc bài **SAU** ngày này):\",\n",
    "    value=date(2026, 3, 15)\n",
    ")\n",
    "\n",
    "# ====================== HÀM CRAWL (giữ nguyên selector cũ của bạn) ======================\n",
    "def crawl_vnexpress(driver, keyword):\n",
    "    data = []\n",
    "    base_url = f\"https://timkiem.vnexpress.net/?search_q={quote(keyword)}\"\n",
    "    st.write(f\"Đang crawl VnExpress: **{keyword}**\")\n",
    "    \n",
    "    for page in range(1, 3):\n",
    "        url = base_url if page == 1 else f\"{base_url}&page={page}\"\n",
    "        driver.get(url)\n",
    "        time.sleep(4)\n",
    "        articles = driver.find_elements(By.CSS_SELECTOR, \"h3.title-news\")\n",
    "        st.write(f\"  VnExpress - Trang {page}: Tìm thấy {len(articles)} bài\")\n",
    "        \n",
    "        for article in articles:\n",
    "            try:\n",
    "                a_tag = article.find_element(By.TAG_NAME, \"a\")\n",
    "                title = a_tag.text.strip()\n",
    "                if keyword.lower() not in title.lower(): continue\n",
    "                link = a_tag.get_attribute(\"href\")\n",
    "                if link and \"vnexpress.net\" in link:\n",
    "                    data.append({'Keyword': keyword, 'Tiêu đề': title, 'Link': link})\n",
    "            except:\n",
    "                continue\n",
    "    return data\n",
    "\n",
    "def crawl_cafef(driver, keyword):\n",
    "    data = []\n",
    "    base_url = f\"https://cafef.vn/tim-kiem.chn?keywords={quote(keyword)}\"\n",
    "    st.write(f\"Đang crawl CafeF: **{keyword}**\")\n",
    "    \n",
    "    for page in range(1, 3):\n",
    "        url = base_url if page == 1 else f\"https://cafef.vn/tim-kiem/trang-{page}.chn?keywords={quote(keyword)}\"\n",
    "        driver.get(url)\n",
    "        time.sleep(4)\n",
    "        \n",
    "        soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "        articles = soup.find_all('a', href=lambda h: h and '.chn' in h and 'tim-kiem' not in h)\n",
    "        st.write(f\"  CafeF - Trang {page}: Tìm thấy {len(articles)} bài\")\n",
    "        \n",
    "        for article in articles:\n",
    "            title = article.text.strip()\n",
    "            if keyword.lower() not in title.lower(): continue\n",
    "            link = article.get(\"href\")\n",
    "            data.append({'Keyword': keyword, 'Tiêu đề': title, 'Link': \"https://cafef.vn\" + link})\n",
    "    return data\n",
    "\n",
    "# ====================== NÚT BẮT ĐẦU ======================\n",
    "if st.button(\"🚀 BẮT ĐẦU CRAWL & LỌC\", type=\"primary\", use_container_width=True):\n",
    "    if not keywords_str:\n",
    "        st.error(\"Vui lòng nhập từ khóa!\")\n",
    "        st.stop()\n",
    "\n",
    "    keywords = [kw.strip() for kw in keywords_str.split(',') if kw.strip()]\n",
    "\n",
    "    # --- CRAWL ---\n",
    "    with st.spinner(\"Đang khởi động Chrome headless và crawl (có thể mất 5-10 phút)...\"):\n",
    "        options = Options()\n",
    "        options.add_argument(\"--headless=new\")\n",
    "        options.add_argument(\"--no-sandbox\")\n",
    "        options.add_argument(\"--disable-dev-shm-usage\")\n",
    "        options.add_argument(\"--window-size=1920,1080\")\n",
    "\n",
    "        driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n",
    "\n",
    "        all_data = []\n",
    "        progress_bar = st.progress(0)\n",
    "\n",
    "        for i, kw in enumerate(keywords):\n",
    "            vn_data = crawl_vnexpress(driver, kw)\n",
    "            all_data.extend(vn_data)\n",
    "            cf_data = crawl_cafef(driver, kw)\n",
    "            all_data.extend(cf_data)\n",
    "            progress_bar.progress((i + 1) / len(keywords))\n",
    "\n",
    "        driver.quit()\n",
    "\n",
    "    df = pd.DataFrame(all_data)\n",
    "    df_clean = df.drop_duplicates(subset=['Tiêu đề'])\n",
    "    df_new = df_clean.copy()\n",
    "\n",
    "    # --- LỌC NGÀY (copy nguyên logic cũ của bạn) ---\n",
    "    st.write(f\"🔍 Đang lọc bài **SAU ngày**: {target_date}\")\n",
    "    headers = {\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\"}\n",
    "\n",
    "    keep_indices = []\n",
    "    article_dates = []\n",
    "    progress_bar2 = st.progress(0)\n",
    "    status = st.empty()\n",
    "\n",
    "    for i, (idx, row) in enumerate(df_new.iterrows()):\n",
    "        status.text(f\"Đang kiểm tra bài {i+1}/{len(df_new)}: {row['Tiêu đề'][:70]}...\")\n",
    "        \n",
    "        url = str(row.get('Link', '')).strip()\n",
    "        if not url or (\"vnexpress.net\" not in url and \"cafef.vn\" not in url):\n",
    "            progress_bar2.progress((i+1)/len(df_new))\n",
    "            continue\n",
    "        \n",
    "        try:\n",
    "            response = requests.get(url, headers=headers, timeout=10)\n",
    "            soup = BeautifulSoup(response.text, 'html.parser')\n",
    "            \n",
    "            date_text = None\n",
    "            meta = soup.find('meta', attrs={'property': 'article:published_time'}) or \\\n",
    "                   soup.find('meta', attrs={'name': ['article:published_time', 'pubdate', 'publishdate']})\n",
    "            if meta and meta.get('content'):\n",
    "                date_text = meta['content']\n",
    "            \n",
    "            if not date_text:\n",
    "                time_tag = soup.find('time')\n",
    "                if time_tag and time_tag.get('datetime'):\n",
    "                    date_text = time_tag['datetime']\n",
    "            \n",
    "            if not date_text:\n",
    "                if \"vnexpress.net\" in url:\n",
    "                    tag = soup.find('span', class_='date') or soup.find('time')\n",
    "                else:\n",
    "                    tag = soup.find('span', class_='pdate') or soup.find('span', class_='time')\n",
    "                if tag:\n",
    "                    date_text = tag.get_text(strip=True)\n",
    "            \n",
    "            if not date_text:\n",
    "                progress_bar2.progress((i+1)/len(df_new))\n",
    "                continue\n",
    "\n",
    "            # === PARSE NGÀY (nguyên bản code cũ) ===\n",
    "            parsed_date = None\n",
    "            iso_match = re.search(r'(\\d{4}-\\d{2}-\\d{2})', date_text)\n",
    "            if iso_match:\n",
    "                try:\n",
    "                    parsed_date = datetime.strptime(iso_match.group(1), \"%Y-%m-%d\").date()\n",
    "                except:\n",
    "                    pass\n",
    "            \n",
    "            if not parsed_date:\n",
    "                dmy_match = re.search(r'(\\d{1,2})[./-](\\d{1,2})[./-](\\d{4})', date_text)\n",
    "                if dmy_match:\n",
    "                    d, m, y = dmy_match.groups()\n",
    "                    try:\n",
    "                        parsed_date = datetime.strptime(f\"{d}/{m}/{y}\", \"%d/%m/%Y\").date()\n",
    "                    except:\n",
    "                        try:\n",
    "                            parsed_date = datetime.strptime(f\"{m}/{d}/{y}\", \"%d/%m/%Y\").date()\n",
    "                        except:\n",
    "                            pass\n",
    "            \n",
    "            if not parsed_date:\n",
    "                parsed = dateparser.parse(date_text, languages=['vi'], settings={'DATE_ORDER': 'DMY'})\n",
    "                if parsed:\n",
    "                    parsed_date = parsed.date()\n",
    "            \n",
    "            if not parsed_date:\n",
    "                progress_bar2.progress((i+1)/len(df_new))\n",
    "                continue\n",
    "            \n",
    "            if parsed_date > target_date:\n",
    "                keep_indices.append(idx)\n",
    "                article_dates.append(parsed_date.strftime(\"%d/%m/%Y\"))\n",
    "            \n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        progress_bar2.progress((i+1)/len(df_new))\n",
    "        time.sleep(0.8)\n",
    "\n",
    "    # === KẾT QUẢ ===\n",
    "    df_filtered = df_new.loc[keep_indices].copy().reset_index(drop=True)\n",
    "    df_filtered['Ngay_ra_tin'] = article_dates\n",
    "\n",
    "    st.success(f\"✅ HOÀN TẤT! Còn lại **{len(df_filtered)} bài** sau ngày {target_date}\")\n",
    "\n",
    "    st.dataframe(df_filtered[['Keyword', 'Tiêu đề', 'Ngay_ra_tin', 'Link']].head(10), use_container_width=True)\n",
    "\n",
    "    df_filtered['Nguồn'] = df_filtered['Link'].apply(lambda x: f'=HYPERLINK(\"{x}\", \"Xem bài báo\")')\n",
    "    df_final = df_filtered[['Keyword', 'Tiêu đề', 'Ngay_ra_tin', 'Nguồn']]\n",
    "\n",
    "    # Download Excel\n",
    "    def convert_to_excel(df):\n",
    "        output = io.BytesIO()\n",
    "        with pd.ExcelWriter(output, engine='openpyxl') as writer:\n",
    "            df.to_excel(writer, index=False)\n",
    "        return output.getvalue()\n",
    "\n",
    "    st.download_button(\n",
    "        label=\"📥 TẢI FILE EXCEL (có hyperlink sẵn)\",\n",
    "        data=convert_to_excel(df_final),\n",
    "        file_name=f\"{keywords[0]}_DDMMYYYY_{target_date}.xlsx\",\n",
    "        mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"\n",
    "    )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
